export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";

export const LOGIN_OK = "LOGIN_OK";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO";
export const SUBIR_ARCHIVO_OK = "SUBIR_ARCHIVO_OK";
export const SUBIR_ARCHIVO_ERROR = "SUBIR_ARCHIVO_ERROR";

export const CREAR_ENLACE_OK = "CREAR_ENLACE_OK";
export const CREAR_ENLACE_ERROR = "CREAR_ENLACE_ERROR";

export const LIMPIAR_STATE = "LIMPIAR_STATE";
